# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-05 08:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CitiesData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name of the city')),
                ('region', models.CharField(max_length=255, verbose_name='Region of the city')),
                ('data', models.IntegerField(verbose_name='Region of the city')),
            ],
            options={
                'verbose_name': 'CitiesData',
                'verbose_name_plural': 'CitiesDatas',
            },
        ),
    ]
